server:
  port: 8020  #指定服务端口

spring:
  application:
    name: microservice-config-server-encrypt-rsa
  cloud:
    config:
      server:
        git:
        #git的项目地址
          uri: https://gitee.com/LoneTraveler/kevin-config-repo
          username:
          password:
encrypt:
  key-store:
    location: classpath:/server-rsa.jks
    password: 123456
    alias: mytest
    secret: a123456 #私钥密码