server:
  port: 8380  #指定服务端口
spring:
  cloud:
    config:
      server:
        git:
        #git的项目地址
          uri: https://gitee.com/LoneTraveler/kevin-config-repo
#配置登录密码
security:
  basic:
    enabled: true
  user:
    name: kevin
    password: 123456