server:
  port: 8381
#测试一：配置服务客户端Client应用入口（正常测试 ConfigClient ）
#prifile: profile-fev(local)

# 测试二：配置服务客户端Client应用入口（链接 ClientServer 测试）
#spring:
#  cloud:
#    config:
#      uri: http://localhost:8082
#      profile: dev
#      label: master #当 ConfigServer 的后端存储的是 Git 的时候，默认就是 master
#
#  application:
#    name: foobar  #取 foobar-dev.yml 这个文件的 application 名字，即为 foobar 名称

# 测试三：配置服务客户端Client应用入口（链接 ClientServer 测试，同时本地也有一份配置文件，那么该如何抉择呢？）
#profile: profile-local-dev