server:
  port: 8180  #指定服务端口

spring:
  application:
    name: microservice-config-server-encrypt
  cloud:
    config:
      server:
        git:
        #git的项目地址
          uri: https://gitee.com/LoneTraveler/kevin-config-repo
          username:
          password:
encrypt:
  #加密时需要使用
  key: foo